# Generated by Django 4.2.28 on 2026-09-26 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='botsession',
            name='bale_user_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
