from django.urls import path

from miniapp import api, api_extra, api_shop
from miniapp.views import manager_app, media_file, mini_app, panel_asset, rules_page

urlpatterns = [
    path('assets/<path:name>', panel_asset, name='miniapp_asset'),
    path('media/<path:name>', media_file, name='miniapp_media'),
    path('rules/', rules_page, name='miniapp_rules'),
    path('', mini_app, name='miniapp_home'),
    path('manager/', manager_app, name='miniapp_manager'),
    path('api/me', api.api_me),
    path('api/me/prefs', api.api_me_prefs),
    path('api/channels/<int:channel_id>/avatar', api.api_channel_avatar),
    path('api/channels', api.api_channels),
    path('api/channels/refresh', api.api_refresh_channel_stats),
    path('api/channels/add', api.api_add_channel),
    path('api/publish-mode', api_shop.api_set_publish_mode),
    path('api/tariffs', api.api_tariffs),
    path('api/tariffs/add', api.api_add_tariff),
    path('api/tariffs/update', api_shop.api_tariff_update),
    path('api/catalog', api_extra.api_catalog),
    path('api/orders', api.api_orders),
    path('api/orders/approve', api_extra.api_order_approve),
    path('api/orders/reject', api_extra.api_order_reject),
    path('api/orders/suggest', api_shop.api_suggest_time),
    path('api/orders/answer', api_shop.api_answer_time),
    path('api/orders/confirm', api_shop.api_order_confirm),
    path('api/orders/published', api_shop.api_order_published),
    path('api/free-days', api.api_free_days),
    path('api/calendar', api_shop.api_calendar),
    path('api/busy', api.api_mark_busy),
    path('api/busy-day', api_shop.api_busy_day),
    path('api/clear-busy', api_shop.api_clear_busy),
    path('api/wallet', api.api_wallet),
    path('api/bank', api.api_add_bank),
    path('api/payout', api.api_request_payout),
    path('api/pay/invoice', api.api_invoice),
    path('api/banners', api_shop.api_banners),
    path('api/banners/<int:banner_id>/media', api_shop.api_banner_media),
    path('api/banners/rename', api_shop.api_banner_rename),
    path('api/banners/hide', api_shop.api_banner_hide),
    path('api/cart', api_shop.api_cart),
    path('api/cart/add', api_shop.api_cart_add),
    path('api/cart/remove', api_shop.api_cart_remove),
    path('api/cart/banner', api_shop.api_cart_banner),
    path('api/checkout', api_shop.api_checkout),
    path('api/my-orders', api_shop.api_my_orders),
    path('api/orders/cancel', api_shop.api_order_cancel),
    path('api/operator/payouts', api_extra.api_operator_payouts),
    path('api/operator/mark-paid', api_shop.api_operator_paid),
    path('api/operator/banners', api_shop.api_operator_banners),
    path('api/operator/banner-decide', api_shop.api_operator_banner_decide),
    path('api/operator/resolve', api_shop.api_operator_resolve),
    path('api/operator/refund', api_shop.api_operator_refund),
]
