# Generated by Django 4.2.28 on 2026-09-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletledger',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status'], name='payout_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='payout_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='walletledger',
            index=models.Index(fields=['user', 'id'], name='ledger_user_id_idx'),
        ),
    ]
