# Generated by Django 4.2 on 2026-10-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletledger_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletledger',
            name='entry_type',
            field=models.CharField(choices=[('earn', 'Earn'), ('refund', 'Refund'), ('penalty', 'Penalty'), ('payout_lock', 'PayoutLock'), ('payout_paid', 'PayoutPaid'), ('payout_unlock', 'PayoutUnlock'), ('spend', 'Spend'), ('escrow', 'Escrow'), ('adjust', 'Adjust')], max_length=20),
        ),
    ]
