# Generated by Django 4.2.28 on 2026-09-26 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('publish_mode', models.CharField(choices=[('bot', 'ارسال خودکار با لینک\u200cساز'), ('linkyar', 'ارسال خودکار با لینک\u200cیار'), ('manual', 'ارسال دستی توسط خودم')], default='bot', help_text='bot=لینک\u200cساز | linkyar=لینک\u200cیار | manual=دستی', max_length=16)),
                ('linkyar_is_admin', models.BooleanField(default=False)),
                ('linkyar_checked_at', models.DateTimeField(blank=True, null=True)),
                ('bot_is_admin', models.BooleanField(default=False)),
                ('bot_checked_at', models.DateTimeField(blank=True, null=True)),
                ('manual_remind_hours', models.PositiveSmallIntegerField(default=2, help_text='ساعت یادآوری قبل از تبلیغ (فقط حالت دستی)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='groups', to='channels_app.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_hour', models.PositiveSmallIntegerField(blank=True, help_text='ساعت شروع نوبت (0-23)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('duration_hours', models.IntegerField()),
                ('price', models.IntegerField(help_text='قیمت به تومان (برای کل مجموعه اگر group باشد)')),
                ('is_active', models.BooleanField(default=True, help_text='اگر ادمین لازم نباشد False می\u200cشود و از فهرست مشتری حذف می\u200cشود')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='channels_app.channel')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='channels_app.channelgroup')),
            ],
        ),
    ]
