# Generated by Django 4.2.28 on 2026-09-26 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroup',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='channels_app.channel'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='channels_app.channelgroup'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='channels_app.tariff'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('channel__isnull', False), ('group__isnull', True)), models.Q(('channel__isnull', True), ('group__isnull', False)), _connector='OR'), name='tariff_channel_xor_group'),
        ),
    ]
