# Generated by Django 4.2.28 on 2026-09-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['tariff', 'start'], name='slot_tariff_start_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['channel', 'start'], name='slot_channel_start_idx'),
        ),
    ]
