# Generated by Django 4.2.28 on 2026-09-26 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_managers', 'WaitingManagers'), ('waiting_customer_confirm', 'WaitingCustomerConfirm'), ('waiting_payment', 'WaitingPayment'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('banner_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_from_chat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('banner_caption', models.TextField(blank=True, default='')),
                ('banner_edit_count', models.PositiveSmallIntegerField(default=0)),
                ('managers_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField()),
                ('manager_status', models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('edited', 'edited'), ('expired', 'expired'), ('customer_declined', 'customer_declined')], default='cart', max_length=20)),
                ('manager_edited_start', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('banner_forwarded', models.BooleanField(default=False)),
                ('banner_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_status', models.CharField(choices=[('none', 'none'), ('paid', 'paid'), ('remind_sent', 'remind_sent'), ('awaiting_manager_publish', 'awaiting_manager_publish'), ('awaiting_customer_confirm', 'awaiting_customer_confirm'), ('awaiting_operator', 'awaiting_operator'), ('executed', 'executed'), ('failed_publish', 'failed_publish'), ('cancelled', 'cancelled')], default='none', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_link', models.CharField(blank=True, default='', max_length=500)),
                ('customer_confirm_deadline', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('channel_message_id', models.TextField(blank=True, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels_app.channel')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_app.tariff'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerresponse',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerresponse',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orders.orderitem'),
        ),
    ]
