# Generated by Django 4.2.28 on 2026-09-26 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_availabilityslot_slot_tariff_start_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_banner_publish_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SlotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='booked_channel_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='order_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['manager_status'], name='item_mgr_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['execution_status'], name='item_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tariff', 'requested_start'], name='item_tariff_start_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['manager', 'manager_status'], name='item_manager_status_idx'),
        ),
        migrations.AddField(
            model_name='slotreservation',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_lock', to='channels_app.availabilityslot'),
        ),
        migrations.AddField(
            model_name='slotreservation',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_lock', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='slotreservation',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='channels_app.tariff'),
        ),
        migrations.AddField(
            model_name='customerdraft',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_draft', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdraft',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_lock', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='slotreservation',
            constraint=models.UniqueConstraint(fields=('tariff', 'slot_date'), name='uniq_tariff_slot_date'),
        ),
        migrations.AddConstraint(
            model_name='slotreservation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('availability__isnull', True), ('order_item__isnull', False)), models.Q(('availability__isnull', False), ('order_item__isnull', True)), _connector='OR'), name='slot_reservation_one_owner'),
        ),
    ]
