# Generated by Django 4.2 on 2026-10-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customerdraft_slotreservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('waiting_banner', 'WaitingBanner'), ('waiting_managers', 'WaitingManagers'), ('waiting_customer_confirm', 'WaitingCustomerConfirm'), ('waiting_payment', 'WaitingPayment'), ('paid', 'Paid'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
    ]
